apiVersion: v1
kind: Service
metadata:
  name: foodie-backend
  namespace: foodie-app
spec:
  type: ClusterIP
  selector:
    app: foodie-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
